x-app: &base-app
  build:
    context: ./backend/
    # args:
    #   - "UID=${UID:-1000}"
    #   - "GID=${GID:-1000}"
  depends_on:
    - db
  env_file:
    - ".env"
  restart: "unless-stopped"

services:
  backend:
    <<: *base-app
    container_name: backend
    command: >
      sh -c "
        python ./manage.py migrate  &&
        daphne -b 0.0.0.0 -p 8000 core.asgi:application
      "
    healthcheck:
      test: curl http://0.0.0.0:8000/ || exit 1
      interval: 1m30s
      timeout: 40s
      retries: 3
      start_period: 30s
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:14.5-bullseye
    container_name: postgres_db
    restart: "unless-stopped"
    ports:
      - 5432
    env_file:
    - "./.env"
    volumes:
      - "db:/var/lib/postgresql/data"

  frontend:
    build:
      context: ./frontend/
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: >
      sh -c "
        serve -s build -l 3000"
    env_file:
      - ./.env
    depends_on:
      - "backend"


volumes:
  db: {}