COMPOSE_NAME_FILE: deployment-compose
MAINTAINER: OSHS

x-app: &backend
  build:
    context: ./backend/
  command: |
    sh -c "
    cd ./backend/core &&
    daphne -b 0.0.0.0 -p 8000 core.asgi:application"
  env_file:
    - .env
  depends_on:
    "postgres"
  ports:
    - ${DOCKER_SERVICE_BACKEND_PORT:-8000:8000}
  restart:
    -${DOCKER_RESTART_POLICY:-unless-stopped}
  volumes:
    - ./backend:/backend

services:
  web:
    <<: *backend
    healthcheck:
      test: sh -c "curl http://localhost:8000" | exit 1
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
      end_period: 10s